version: '3'
services:

  mongodb:
    image: mongo
    networks:
      - penguin-network
    ports:
      - "27017"
    volumes:
      - "~/data:/data/db"

  penguin-api:
    build:
      dockerfile: ./penguin-api/Dockerfile
      context: .
    image: penguin-formula/penguin-api
    container_name: penguin-api
    ports:
      - "3000:3000"
    networks:
      - penguin-network
    depends_on:
      - "mongodb"

  penguin-frontend:
    build:
      dockerfile: ./penguin-frontend/Dockerfile
      context: .
    image: penguin-formula/penguin-frontend
    container_name: penguin-frontend
    ports:
      - "3001:3001"
    networks:
      - penguin-network
    depends_on:
      - "penguin-api"
      
networks:
  penguin-network:
    driver: bridge
