version: '3'
services:

  mongodb-service:
    image: mongo
    networks:
      - penguin-network
    ports:
      - "27017"
    volumes:
      - "~/data:/data/db"

  penguin-api:
    build:
      dockerfile: ./Dockerfile
      context: ./penguin-api
    image: penguinformula/penguin-api
    container_name: penguin-api
    ports:
      - "3000:3000"
    networks:
      - penguin-network
    depends_on:
      - "mongodb-service"

  penguin-frontend:
    build:
      dockerfile: ./Dockerfile
      context: ./penguin-frontend
    image: penguinformula/penguin-frontend
    container_name: penguin-frontend
    ports:
      - "5000:5000"
    networks:
      - penguin-network
    depends_on:
      - "penguin-api"
      
networks:
  penguin-network:
    driver: bridge
